### ISSUE TITLE
Is this project working well in windows version of Sigrok?

### ISSUE THREAD

**Issue by DeqingSun** [tannewt/tinylogicfriend#2]
Hi. I tried to do something similar with CH552 but it got constant crashing on the second captures and other places. I even tried the Arduino Uno implementation with similar problem.

Does this implementation works well in Windows? If so, would you mind sharing your Sigrok version?

**Comment by tannewt** [comment]
Its been a while since I even tried this. So, I don't know the state of sigrok at all. Sorry!

**Comment by DeqingSun** [comment]
That's fine, thank you.
